<?php

namespace AppBundle\Repository;

/**
 * IdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentityRepository extends \Doctrine\ORM\EntityRepository
{
}
